<?php
/**
 * Template Name: Developer Guide
 *
 * Renders CREATING-A-BLOCK.md (the step-by-step block guide in the theme root)
 * as a page, with a sticky contents list built from its headings.
 *
 * The markdown file stays the single source of truth: edit the .md, the page
 * updates. Nothing is stored in the page itself, so any block content added to
 * the page in the editor is ignored.
 *
 * Only users who can edit posts can read it. Everyone else gets a short
 * sign-in prompt so internal file paths and team notes are not public.
 *
 * To use: Pages → Add New → title it (e.g. "Creating a block") → Template:
 * Developer Guide → Publish.
 */

require_once get_template_directory() . '/inc/markdown.php';

$guide_file = get_template_directory() . '/CREATING-A-BLOCK.md';
$can_view   = current_user_can( 'edit_posts' );
$doc        = null;

if ( $can_view && file_exists( $guide_file ) ) {
    $doc = theme_markdown_to_html( file_get_contents( $guide_file ) );
}

// Enqueued here (after wp_head) so it prints in the footer via print_late_styles().
wp_enqueue_style(
    'app-developer-guide',
    get_template_directory_uri() . '/css/developer-guide.css',
    [ 'app-theme' ],
    theme_asset_version( 'css/developer-guide.css' )
);

get_header();
?>

<main class="dev-guide">
    <div class="container">

        <?php if ( ! $can_view ) : ?>

            <div class="dev-guide-locked">
                <h1><?php the_title(); ?></h1>
                <p><?php esc_html_e( 'This page is for the site\'s development team.', 'base-theme' ); ?></p>
                <p><a class="btn btn--primary" href="<?php echo esc_url( wp_login_url( get_permalink() ) ); ?>"><?php esc_html_e( 'Sign in to read it', 'base-theme' ); ?></a></p>
            </div>

        <?php elseif ( ! $doc ) : ?>

            <div class="dev-guide-locked">
                <h1><?php the_title(); ?></h1>
                <p><?php esc_html_e( 'CREATING-A-BLOCK.md was not found in the theme folder.', 'base-theme' ); ?></p>
            </div>

        <?php else : ?>

            <div class="dev-guide-layout">

                <aside class="dev-guide-toc" aria-label="<?php esc_attr_e( 'Contents', 'base-theme' ); ?>">
                    <p class="dev-guide-toc-label"><?php esc_html_e( 'Contents', 'base-theme' ); ?></p>
                    <ol>
                        <?php foreach ( $doc['headings'] as $h ) : ?>
                            <?php if ( 2 !== $h['level'] ) { continue; } ?>
                            <li><a href="#<?php echo esc_attr( $h['id'] ); ?>"><?php echo theme_markdown_inline( $h['text'] ); ?></a></li>
                        <?php endforeach; ?>
                    </ol>
                    <p class="dev-guide-toc-source">
                        <?php
                        printf(
                            /* translators: %s: file name */
                            esc_html__( 'Source: %s in the theme folder. Edit that file to update this page.', 'base-theme' ),
                            '<code>CREATING-A-BLOCK.md</code>'
                        );
                        ?>
                    </p>
                </aside>

                <article class="dev-guide-content">
                    <?php
                    // Output is generated by theme_markdown_to_html(), which escapes
                    // all text from the file before adding its own markup.
                    echo $doc['html']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
                    ?>
                </article>

            </div>

        <?php endif; ?>

    </div>
</main>

<?php get_footer(); ?>
